version: "3.8"

services:

  university_db:
    container_name: university_db
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db

  university_pgadmin:
    container_name: university_pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    depends_on:
      - university_db

  university_api:
    container_name: university_api
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - src/.env
    depends_on:
      - university_db


  university_api_generate:
    container_name: university_api_generate
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - .:/app
    env_file:
      - src/.env
    command: "python -m src.tables.generate_all"
    depends_on:
      - university_api

