"""add faculty

Revision ID: 0b623c4c5c17
Revises: 1961c26774b9
Create Date: 2022-12-07 19:03:00.177945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b623c4c5c17'
down_revision = '1961c26774b9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор записи факультета'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название факультета'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Факультеты'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('faculty')
    # ### end Alembic commands ###
