"""add group

Revision ID: 21d52e8d6553
Revises: 896eaff00b5b
Create Date: 2022-12-07 19:14:51.802150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d52e8d6553'
down_revision = '896eaff00b5b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор записи группы'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название группы'),
    sa.Column('course', sa.Integer(), nullable=False, comment='Курс группы'),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('housing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['housing_id'], ['housing.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Группы'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group')
    # ### end Alembic commands ###
