"""add student

Revision ID: 46ff4e3e048c
Revises: d55d6961087a
Create Date: 2022-12-07 19:15:18.211099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46ff4e3e048c'
down_revision = 'd55d6961087a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
