"""add subject

Revision ID: 85f0f9454ced
Revises: 46ff4e3e048c
Create Date: 2022-12-07 19:17:09.337427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f0f9454ced'
down_revision = '46ff4e3e048c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор записи Предмета'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Название Предмета'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    comment='Предметы'
    )
    op.create_table('group_subject',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], )
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор записи Студента'),
    sa.Column('first_name', sa.String(length=255), nullable=False, comment='Имя Студента'),
    sa.Column('second_name', sa.String(length=255), nullable=False, comment='Отчество Студента'),
    sa.Column('family', sa.String(length=255), nullable=False, comment='Фамилия Студента'),
    sa.Column('age', sa.Integer(), nullable=False, comment='Возраст Студента'),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Студенты'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    op.drop_table('group_subject')
    op.drop_table('subject')
    # ### end Alembic commands ###
