"""add group_subject

Revision ID: d55d6961087a
Revises: 21d52e8d6553
Create Date: 2022-12-07 19:15:03.112508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd55d6961087a'
down_revision = '21d52e8d6553'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
