"""add student_info

Revision ID: e3598f520806
Revises: 85f0f9454ced
Create Date: 2022-12-07 19:17:27.496883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3598f520806'
down_revision = '85f0f9454ced'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_info',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор записи Информация о студенте'),
    sa.Column('description', sa.String(), nullable=False, comment='описание'),
    sa.Column('address', sa.String(), nullable=False, comment='адрес'),
    sa.Column('img', sa.String(), nullable=False, comment='картинка'),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    comment='Информация о студенте'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_info')
    # ### end Alembic commands ###
