"""add student table

Revision ID: 2a519f2786fc
Revises: a5f4f1bc707b
Create Date: 2022-12-22 18:07:11.041429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a519f2786fc'
down_revision = 'a5f4f1bc707b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор записи Студента'),
    sa.Column('first_name', sa.String(length=255), nullable=False, comment='Имя Студента'),
    sa.Column('second_name', sa.String(length=255), nullable=False, comment='Отчество Студента'),
    sa.Column('family', sa.String(length=255), nullable=False, comment='Фамилия Студента'),
    sa.Column('age', sa.Integer(), nullable=False, comment='Возраст Студента'),
    sa.PrimaryKeyConstraint('id'),
    comment='Студенты'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
