"""add student table

Revision ID: c784c4c751de
Revises: f0673b578993
Create Date: 2023-01-10 18:37:51.154723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c784c4c751de'
down_revision = 'f0673b578993'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор записи Студента'),
    sa.Column('first_name', sa.String(length=255), nullable=False, comment='Имя Студента'),
    sa.Column('second_name', sa.String(length=255), nullable=False, comment='Отчество Студента'),
    sa.Column('family', sa.String(length=255), nullable=False, comment='Фамилия Студента'),
    sa.Column('age', sa.Integer(), nullable=False, comment='Возраст Студента'),
    sa.PrimaryKeyConstraint('id'),
    comment='Студенты'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
