"""add user table

Revision ID: f0673b578993
Revises: 52f46952c051
Create Date: 2023-01-10 18:36:53.211013

"""
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0673b578993'
down_revision = '52f46952c051'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.drop_index('ix_student_user_id', table_name='student')
    op.drop_table('student')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False, comment='Идентификатор записи Студента'),
    sa.Column('first_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Имя Студента'),
    sa.Column('second_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Отчество Студента'),
    sa.Column('family', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Фамилия Студента'),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=False, comment='Возраст Студента'),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True, comment='Идентификатор пользователя'),
    sa.PrimaryKeyConstraint('id', name='student_pkey'),
    comment='Студенты'
    )
    op.create_index('ix_student_user_id', 'student', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
